import axios from 'axios';

const urls = [
  "https://onlinemedicalcardnewmexico.com/",
  "https://onlinemedicalcardnewyork.com/",
  "https://medicalcardpennsylvania.com/",
  "https://montanammjcard.com/",
  "https://mmjcardwashington.com/",
  "https://mdwestvirginia.com/",
  "https://medicalcardnewjersey.com/",
  "https://mdmassachusetts.com/",
  "https://marylandmmjcard.com/",
  "https://mainemedicalcardonline.com/",
  "https://medicalcardiowa.com/",
  "https://medicalcarddelaware.com/",
  "https://mdconnecticut.com/",
  "http://onlinethcstore.com/",
  "https://texasmarijuanacardonline.com/",
  "https://marijuanacardbakersfield.com/",
  "https://norfolkmmjcarddoctor.com/",
  "https://chesapeakemmjcarddoctor.com/",
  "https://virginiabeachmmjcarddoctor.com/",
  "https://minneapolismmjcarddoctor.com/",
  "https://shreveportmmjcarddoctor.com/",
  "https://batonrougemmjcarddoctor.com/",
  "https://neworleansmmjcarddoctor.com/",
  "https://parkersburgmmjcarddoctor.com/",
  "https://huntingtonmmjcarddoctor.com/",
  "https://sanantoniommjcarddoctor.com/",
  "https://dallasmmjcarddoctor.com/",
  "https://charlestonmmjcarddoctor.com/",
  "https://chicagommjcarddoctor.com/",
  "https://napervillemmjcarddoctor.com/",
  "https://bridgeportmmjcarddoctor.com/",
  "https://stamfordmmjcarddoctor.com/",
  "https://newhavenmmjcarddoctor.com/",
  "https://schaumburgmmjcarddoctor.com/",
  "http://davenportmmjcarddoctor.com/",
  "https://houstonmmjcarddoctor.com/",
  "https://newyorkcitymmjcarddoctor.com/",
  "https://westvirginiammjcarddoctor.com/",
  "https://cedarrapidsmmjcarddoctor.com/",
  "https://desmoinesmmjcarddoctor.com/",
  "https://californiaonlineclinic.com/",
  "https://iowammjcarddoctor.com/",
  "https://mymmjcard.com/",
  "https://weedtome.com/",
  "https://pennsylvaniammjcarddoctor.com/",
  "https://michiganmmjcarddoctor.com/",
  "https://minnesotammjcarddoctor.com/",
  "https://raodechina.com/",
  "https://thcdoctorssalinas.com/",
  "https://medicalmarijuanacardstockton.com/",
  "https://onlinemedicalrec.com/",
  "https://mjgreencardsyonkersny.com/",
  "http://torrance420dr.com/",
  "https://palmdalealternativemedcenter.com/",
  "https://bronxnymedical420doctors.com/",
  "http://marijuanadrsantamonica.com/",
  "http://vallejo420medical.com/",
  "https://onlinemedicalevaluations.com/",
  "https://420doctorsoklahoma.us/",
  "https://californiamarijuanadoctor.com/",
  "http://oklahomahealing420.com/",
  "https://onlinecannadoc.com/",
  "https://mdganja.com/",
  "http://420marijuanacardfullerton.com",
  "https://medicalmarihuanadoctor.com/",
  "https://www.onlinemedicalcard.com/",
  "https://mdoklahoma.com/",
  "https://ohiomedicalcards.com/",
  "https://mdmissouri.com/",
  "https://mdminnesota.com/",
  "https://mdmichigan.com/",
  "http://westvirginiacannabiscards.com/",
  "https://syracuse420doctors.com/",
  "https://getmyesa.com/",
  "https://cannamdfremont.com/",
  "http://esaletterhouston.com/",
  "http://portlandesadoctors.com/",
  "https://esaletterflorida.com/",
  "https://kifmd.com/",
  "https://greenmdillinois.com/",
  "https://www.medicalcannabiscardsandiego.com/",
  "https://cannabiscardstatenisland.com/",
  "https://ilovemyesa.com/",
  "https://esaletterny.com/",
  "https://rosevillemedicinal420doctor.com/",
  "https://medicalmarijuanacardriverside.com/",
  "https://mmjgardengrove.com/",
  "https://nevadammjcarddoctor.com/",
  "https://ohiommjcarddoctor.com/",
  "https://onlinemedicalclinics.com/",
  "https://murrieta420recommendations.com/",
  "https://santaclara420healing.com/",
  "https://nymedicalcard.com/",
  "https://eddoctoronline.com/",
  "http://santaanamedicalclinic.com/",
  "https://rochester420clinicians.com/",
  "https://chulavistammj.com/",
  "https://santamariathcdr.com/",
  "https://greenmedmdbrooklyn.com/",
  "https://herbalmdwhiteplains.com/",
  "https://healing420temecula.com/",
  "https://mmjcardsoxnard.com/",
  "https://concord420card.com/",
  "https://morenovalleymd.com/",
  "https://longbeachmmjmds.com/",
  "https://cannacancurefresno.com/",
  "https://sanjosemedicalmarijuanacard.com/",
  "https://yubacityganjadoctors.com/",
  "https://mjmdnewportbeach.com/",
  "https://medicalmarijuanacardsanfrancisco.com/",
  "https://medicalmarijuanacardanaheim.com/",
  "https://cannacancurefresno.com/",
  "https://onlinecbdstore.com/",
  "http://phoenixcannabisdr.com",
  "http://my420cardbronx.com/",
  "http://novatoalleviatemmjdr.com/",
  "http://arcadiaalleviatecannabisdoctors.com/",
  "https://santaclaritaherbalrx.com",
  "https://santabarbara420dr.com/",
  "https://medicalmarijuanacardoakland.com/",
  "https://420medicalcardonline.com/",
  "https://www.onlinemmjlosangeles.com/",
  "https://onlinemmjsacramento.com/",
  "https://huntington420doctor.com/",
  "https://ontariommjrecommendations.com/",
  "https://tracysimple420cards.com/",
  "https://medicalmmjdrmodesto.com/",
  "https://drgreennormanok.com/",
  "https://esaletterusa.com/",
  "https://brooklynmarijuanacardsdirect.com/",
  "https://420cardsantarosa.com/",
  "https://lancasterthcmarijuanadoctors.com/",
  "https://alamedafastcannabiscards.com/",
  "https://queensny420evaluations.com/",
  "https://oceansideblissmmjcards.com/",
  "https://nourishmentbynature.com/",
  "http://myesadoctor.com/",
  "https://steadycaremedical.com/",
  "https://420medicalcardonline.com/apply-medical-marijuana-card-instantly/",
  "https://www.mdlouisana.com/",
  "https://www.onlinemedicalcardny.com/",
  "https://www.onlinemedicalcardpennsylvania.com/",
  "https://www.md-texas.com/",
];

const searchLine = process.argv[2];

if (!searchLine) {
  console.error('Please provide a line of code to search for.');
  process.exit(1);
}

const checkCode = async (url) => {
  try {
    const response = await axios.get(url);
    const html = response.data;
    if (html.includes(searchLine)) {
      console.log(`Found in ${url}`);
    }
  } catch (error) {
    console.error(`Error checking ${url}:`, error.message);
  }
};

urls.forEach((url) => checkCode(url));
